name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'transcript/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: |
          npm install

      - name: Clean up old files in the transcript folder
        run: |
          echo "Cleaning up old files..."
          TRANSCRIPT_DIR="./transcript"
          if [ -d "$TRANSCRIPT_DIR" ]; then
            echo "Directory $TRANSCRIPT_DIR exists."
            echo "Looking for files in $TRANSCRIPT_DIR"
            ls -l $TRANSCRIPT_DIR
            echo "Finding files older than 30 days..."
            find $TRANSCRIPT_DIR -type f -mtime +30 -exec echo "Deleting: {}" \; -exec rm -f {} \;
            echo "Cleanup complete."
          else
            echo "Directory $TRANSCRIPT_DIR does not exist. Exiting."
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./transcript
